### PR TITLE
return 400 when error came from Joi

### PR DESCRIPTION
**Pull request by lironess**
returning 500 from a validation for an API request does not make sense. instead we should return 400

### CODE REVIEW

**Comment by msteckyefantis** [comment]
https://github.com/vandium-io/vandium-node/pull/32/commits/a4760eff3a53b124cf20c9d4f04633402feaa0fa#diff-a06118553824189de7a34ee654aace3aR20


```.js
         if( result.error ) {
 
-            throw result.error;
+            throw { statusCode: 400, name: result.error.name, message: result.error };
```

should you be setting the error message as the error object?😐

shoutout to: @richardhyatt 🎅🏿

**Comment by richardhyatt** [comment]
I've reverted the code back to the original state and moved the setting of `statusCode` to `400` to the event handler that processes api gateway events.

**Comment by richardhyatt** [comment]
Now merged into the 4.x release if you would like to verify that it works as intended. Thanks

**Comment by msteckyefantis** [comment]
@richardhyatt I'll try it out soon and let you know if it works

**Comment by msteckyefantis** [comment]
It works👍🏿👍🏽👍🏻👩🏿👩🏽👩🏻🙆🏿🙆🏽🙆🏻

[Here is video evidence](https://gyazo.com/0a168ab03fb7bfdec9b54075689c1afb)🎥✅

**Pull request merged**
